# Generated by Django 5.2.10 on 2026-02-12 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('delimitacion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comun', models.CharField(max_length=50)),
                ('nombre_cient', models.CharField(blank=True, max_length=50, null=True)),
                ('familia', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alcorque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo'), ('NECESITA_INTERVENCION', 'Necesita intervención')], default='BUENO', max_length=50)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alcorque', to='inventario.barrio')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('latitud', 'longitud'), name='un_alcorque_por_ubi')],
            },
        ),
        migrations.CreateModel(
            name='Arbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo'), ('NECESITA_INTERVENCION', 'Necesita intervención')], default='BUENO', max_length=50)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('fecha_plant', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arboles', to='inventario.barrio')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arboles', to='inventario.especie')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('latitud', 'longitud'), name='un_arbol_por_ubi')],
            },
        ),
    ]
