# Generated by Django 6.0.4 on 2026-04-27 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('delimitacion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comun', models.CharField(max_length=50)),
                ('nombre_cient', models.CharField(max_length=50)),
                ('familia', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('arbol', 'Arbol'), ('alcorque', 'Alcorque')], default='arbol', max_length=30)),
                ('estado', models.CharField(choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo'), ('urgente', 'Urgente')], default='bueno', max_length=30)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True)),
                ('direccion', models.CharField(blank=True, max_length=40)),
                ('fecha_plant', models.DateField(null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('potencial_plant', models.CharField(choices=[('apto', 'Apto'), ('no_apto', 'No apto')], default='apto', max_length=30, null=True)),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.barrio')),
                ('especie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.especie')),
            ],
        ),
    ]
