# Generated by Django 5.2.10 on 2026-04-01 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alcorque',
            name='potencial_plant',
            field=models.CharField(choices=[('APTO', 'Apto'), ('NO_APTO', 'No apto')], default='APTO', max_length=10),
        ),
        migrations.AlterField(
            model_name='alcorque',
            name='barrio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alcorques', to='inventario.barrio'),
        ),
        migrations.AlterField(
            model_name='arbol',
            name='fecha_plant',
            field=models.DateField(blank=True, null=True),
        ),
    ]
