# Generated by Django 6.0.4 on 2026-04-27 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemento',
            name='especie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.especie'),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='fecha_plant',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='potencial_plant',
            field=models.CharField(blank=True, choices=[('apto', 'Apto'), ('no_apto', 'No apto')], default='apto', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='tipo',
            field=models.CharField(choices=[('arbol', 'Árbol'), ('alcorque', 'Alcorque')], default='arbol', max_length=30),
        ),
    ]
