# Generated by Django 6.0.4 on 2026-05-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_elemento_especie_alter_elemento_fecha_plant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemento',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=22, null=True),
        ),
    ]
