# Generated by Django 6.0.4 on 2026-05-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_elemento_latitud_alter_elemento_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemento',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=17, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=17, max_digits=22, null=True),
        ),
    ]
