# Generated by Django 6.0.4 on 2026-04-28 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidencias', '0002_alter_incidencia_admin_resp_alter_incidencia_grado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INCIDENCIA', 'Incidencia'), ('ESTADO', 'Cambio de estado'), ('SISTEMA', 'Aviso del sistema')], max_length=30)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField()),
                ('incidencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='incidencias.incidencia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notificado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
