# Generated by Django 6.0.4 on 2026-04-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificaciones',
            name='leida',
            field=models.BooleanField(default=False),
        ),
    ]
