# Generated by Django 6.0.4 on 2026-04-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0003_alter_notificaciones_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificaciones',
            name='tipo',
            field=models.CharField(choices=[('INCIDENCIA_CREADA', 'Incidencia creada correctamente'), ('INCIDENCIA_MODIFICADA', 'Su incidencia ha sido actualizada'), ('ESTADO', 'Cambio de estado'), ('SISTEMA', 'Aviso del sistema')], max_length=30),
        ),
    ]
