# Generated by Django 6.0.4 on 2026-04-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0005_alter_notificaciones_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificaciones',
            name='tipo',
            field=models.CharField(choices=[('INCIDENCIA_CREADA', 'Incidencia creada correctamente'), ('INCIDENCIA_MODIFICADA', 'Su incidencia ha sido actualizada'), ('INCIDENCIA_RESPONSABLE', 'Has sido seleccionado como responsable para una incidencia'), ('ESTADO', 'Cambio de estado'), ('SISTEMA', 'Aviso del sistema'), ('PERFIL_MODIFICAD', '¡Su perfil ha sido modificado correctamente!')], max_length=30),
        ),
    ]
