# Generated by Django 6.0.4 on 2026-05-04 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0003_alter_incidencia_estado'),
        ('notificaciones', '0006_alter_notificaciones_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificaciones',
            name='incidencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='incidencias.incidencia'),
        ),
        migrations.AlterField(
            model_name='notificaciones',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificado', to=settings.AUTH_USER_MODEL),
        ),
    ]
