version: '3.9'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '55432:55432'

  # decidim:
  #   build: ./decidim_app
  #   environment:
  #     DATABASE_URL: postgres://postgres:postgres@postgres:5432/decidim
  #   depends_on:
  #     - postgres
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - ./decidim_app:/app

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/backend
    depends_on:
      - postgres
    ports:
      - '4000:4000'
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - '5173:5173'
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src

  # flask:
  #   build: ./flask
  #   ports:
  #     - '4001:4001'
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - ./flask:/app

volumes:
  postgres_data: