version: '3'
services:
  app:
    image: decidim/decidim:0.29.3
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
    environment:
      - PORT=${puerto1}
      - DATABASE_URL=postgres://postgres:postgres@host.docker.internal:55432/decidim_${NOMBRE}
      - RAILS_ENV=development
    ports:
      - ${puerto1}:3000
    command: bundle exec puma
  pg:
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  node_modules: {}
  bundle: {}
