# Generated by Django 5.2.10 on 2026-04-16 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudBaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('motivo', models.TextField(blank=True, help_text='Motivo opcional de la baja', null=True)),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True)),
                ('comentario_admin', models.TextField(blank=True, help_text='Comentarios del administrador', null=True)),
                ('admin_que_proceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_baja_procesadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_baja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-fecha_solicitud',),
            },
        ),
    ]
