# Generated by Django 5.2.10 on 2026-01-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='fecha_registrado',
            new_name='fecha_registro',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('REGISTRADO', 'Registrado'), ('ADMINISTRADOR', 'Administrador')], default='REGISTRADO', max_length=80),
        ),
    ]
