# Generated by Django 5.2.10 on 2026-02-12 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('descripcion', models.TextField()),
                ('grado_incidencia', models.CharField(choices=[('LEVE', 'Leve'), ('MEDIO', 'Medio'), ('GRAVE', 'Grave')], default='LEVE', max_length=30)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('fecha_act', models.DateTimeField(auto_now=True, null=True)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('EN_PROCESO', 'En proceso'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=30)),
                ('foto_url', models.TextField(blank=True, null=True)),
                ('admin_resp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_inci', to=settings.AUTH_USER_MODEL)),
                ('alcorque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alcorque_inci', to='inventario.alcorque')),
                ('arbol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='arbol_inci', to='inventario.arbol')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usu_incidencia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('arbol__isnull', False), ('alcorque__isnull', True)), models.Q(('arbol__isnull', True), ('alcorque__isnull', False)), _connector='OR'), name='check_arbol_alcorque_incidencia')],
            },
        ),
    ]
