# Generated by Django 6.0.4 on 2026-04-27 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('descripcion', models.TextField()),
                ('grado', models.CharField(choices=[('leve', 'Leve'), ('medio', 'Medio'), ('grave', 'Grave')], default='leve', max_length=30)),
                ('fecha_reporte', models.DateField(auto_now_add=True)),
                ('fecha_act', models.DateField(auto_now=True)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('en_proceso', 'En proceso'), ('cerrada', 'Cerrada')], default='abierta', max_length=30)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='incidencias/')),
                ('admin_resp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_responsable', to=settings.AUTH_USER_MODEL)),
                ('elemento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.elemento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
