# Generated by Django 5.2.10 on 2026-04-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidencia',
            name='foto_url',
        ),
        migrations.AddField(
            model_name='incidencia',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='incidencias/'),
        ),
    ]
