# Generated by Django 6.0.4 on 2026-04-28 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='admin_resp',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_responsable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='grado',
            field=models.CharField(choices=[('leve', 'Leve'), ('medio', 'Medio'), ('grave', 'Grave'), ('urgente', 'Urgente')], default='leve', max_length=30),
        ),
    ]
