# Generated by Django 6.0.4 on 2026-04-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0002_alter_incidencia_admin_resp_alter_incidencia_grado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('abierta', 'Abierta'), ('en_proceso', 'En proceso'), ('cerrada', 'Cerrada')], default='pendiente', max_length=30),
        ),
    ]
