# Generated by Django 5.2.10 on 2026-04-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0002_remove_incidencia_foto_url_incidencia_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='observaciones_internas',
            field=models.TextField(blank=True, help_text='Solo visible para administradores', null=True),
        ),
    ]
